### ISSUE TITLE
Use url function in css

### ISSUE THREAD

**Issue by slavafyi** [slavafyi/vite-plugin-shopify-import-maps#2]
When importing assets from css files (e.g. fonts, images) the import map is not respected.

# Expected behavior

```css
@font-face {
    font-family: Anton;
    font-style: normal;
    font-weight: 400;
    src: url(./anton-v23-latin-regular.woff2) format("woff2"),
         url(./anton-v23-latin-regular.woff) format("woff");
    font-display: swap
}
```

The request url for the font should be as follows:

```
https://store.myshopify.com/cdn/shop/t/32/assets/anton-v23-latin-regular.woff2?v=24123412342134
```

# Actual behavior

The request url for the font:

```
https://store.myshopify.com/cdn/shop/t/32/assets/anton-v23-latin-regular.woff2
```

# Suggestion

A possible solution could be to always use a hash for asset files.

```ts
// vite.config.js
// ... options
build: {
  rollupOptions: {
    output: {
      entryFileNames: '[name].js'
      chunkFileNames: '[name].js'
      assetFileNames: '[name]-[hash].[ext]'
    }
  }
}
```

**Comment by montalvomiguelo** [comment]
This is probably out of the scope of import maps since they are primarily designed to manage JavaScript modules.

An alternate approach could be loading assets like fonts and images from Liquid files using the `asset_url` filter and consuming them via CSS variables. 

```liquid
{% #theme.liquid %}
{% style %}
  @font-face {
    font-family: 'Anton';
    src: url("{{ 'anton-v23-latin-regular.woff2' | asset_url }}") format('woff2');
    font-display: swap;
  }

  :root {
    --font-heading-family: 'Anton', sans-serif;
    --background-image: url('{{ 'background-image.svg' | asset_url }}');
  }
{% endstyle %}
```

```css
/* entrypoints/theme.css */
h1, h2, h3 { font-family: var(--font-heading-family); }
body { background-image: var(--background-image); }
```
